const productsTypes = {
  ADD_NEW_PRODUCT_START: 'ADD_NEW_PRODUCT_START',
  FETCH_PRODUCTS_START: 'FETCH_PRODUCTS_START',
  SET_PRODUCTS: 'SET_PRODUCTS',
  EDIT_PRODUCT_START: 'EDIT_PRODUCT_START', // EDIT
  EDIT_PRODUCT_SUCCESS: 'EDIT_PRODUCT_SUCCESS', // EDIT
  DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
  FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
  SET_PRODUCT: 'SET_PRODUCT',
}

export default productsTypes
